### ISSUE TITLE
Missing Dataframe Column "ts" when trying to run the Docker build

### ISSUE THREAD

**Issue by herrfeder** [herrfeder/AI_Cybersecurity_IDS_PoC#2]
When trying to run the Container following the Instructions in the README, this error occurs:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.8/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.8/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/datascientist/AI_Cybersecurity_IDS_PoC/app/app.py", line 33, in <module>
    dh.update_source("conn")
  File "/home/datascientist/AI_Cybersecurity_IDS_PoC/app/data_helper.py", line 142, in update_source
    self.convert_zeek_df("temp")
  File "/home/datascientist/AI_Cybersecurity_IDS_PoC/app/data_helper.py", line 220, in convert_zeek_df
    self.convert_epoch_ts(file_type)
  File "/home/datascientist/AI_Cybersecurity_IDS_PoC/app/data_helper.py", line 229, in convert_epoch_ts
    if not isinstance(self.df_d[file_type]["ts"][0],pd.Timestamp):
  File "/usr/local/lib/python3.8/site-packages/pandas/core/frame.py", line 2800, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/usr/local/lib/python3.8/site-packages/pandas/core/indexes/numeric.py", line 508, in get_loc
    return super().get_loc(key, method=method, tolerance=tolerance)
  File "/usr/local/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 2648, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 111, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 140, in pandas._libs.index.IndexEngine.get_loc
KeyError: 'ts'
[2021-01-29 08:53:32 +0000] [8] [INFO] Worker exiting (pid: 8)
[2021-01-29 08:53:32 +0000] [6] [INFO] Shutting down: Master
[2021-01-29 08:53:32 +0000] [6] [INFO] Reason: Worker failed to boot.
```

This is the first column in the Zeek log-file `conn.log`. I was assuming, this error should be resolved with this commit https://github.com/herrfeder/AI_Cybersecurity_IDS_PoC/commit/d88435e992b7bf327bd4ebfcbfcfaae169d0627f but it isn't. The problem is, I cannot reproduce it in my Theia IDE with an freshly cloned repo. Should be exactly the same workflow.

Will take some time ( please be gentle, it is right now a hobby project :) )

**Comment by herrfeder** [comment]
I deleted this error by removing the initial update when starting the app (because it's useless) with this commit https://github.com/herrfeder/AI_Cybersecurity_IDS_PoC/commit/7f7c631606c3e2d4069e92eeba45d099484d05fc .
